---
services:
  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana_app
    restart: always
    env_file:
      - .env
    ports:
     - 3000:3000
    volumes:
#      - ./volumes/grafana.ini/grafana.ini:/etc/grafana/grafana.ini
      - ./volumes/grafana-storage:/var/lib/grafana
    networks:
      - grafana_net

volumes:
  grafana-storage: {}

networks:
  grafana_net:
    driver: bridge